import type { NutritionValues } from "#/lib/meal-nutrition-contract";
import type { PortionSize, PortionUnit } from "#/lib/meal-portion-confirmation-contract";
import { normalizeCatalogueLabel, type NutritionCatalogueFood, type NutritionPortionConversion } from "#/lib/server/nutrition-catalogue-schema";

export const EXPANDED_NUTRITION_CATALOGUE_VERSION = "india-plant-starter-v1-2026-07-23";
const IMPORT_DATE = "2026-07-23";

type FoodInput = {
  fdcId: number; canonicalName: string; sourceDescription: string;
  category: NutritionCatalogueFood["category"]; preparationState: NutritionCatalogueFood["preparationState"];
  aliases: string[]; nutrients: NutritionValues; conversions?: NutritionPortionConversion[];
};

function usda(input: FoodInput): NutritionCatalogueFood {
  return {
    id: `usda-fdc-${input.fdcId}`, catalogueVersion: EXPANDED_NUTRITION_CATALOGUE_VERSION,
    canonicalName: input.canonicalName, normalizedName: normalizeCatalogueLabel(input.canonicalName), category: input.category,
    preparationState: input.preparationState, calculationMethod: "single_food", aliases: input.aliases,
    nutrientBasis: { referenceAmount: 100, referenceUnit: "g_edible_portion", energyUnit: "kcal", carbohydrateDefinition: "carbohydrate_by_difference", fibreDefinition: "total_dietary_fibre" },
    nutrientsPer100g: input.nutrients, conversions: input.conversions ?? [],
    provenance: { sourceName: "USDA FoodData Central", sourceIdentifier: `FDC ${input.fdcId}`, dataType: "SR Legacy", sourceDescription: input.sourceDescription, importDate: IMPORT_DATE },
  };
}

function measure(unit: PortionUnit, referenceAmountG: number, sourcePortionId: number, sourcePortionDescription: string, sourceAmount = 1, sourceGramWeight = referenceAmountG * sourceAmount) {
  const source = { unit, referenceAmountG, sourcePortionId: `FDC portion ${sourcePortionId}`, sourcePortionDescription, sourceAmount, sourceGramWeight };
  return [source, { ...source, size: "standard" as const }];
}
function sized(unit: PortionUnit, size: PortionSize, referenceAmountG: number, sourcePortionId: number, sourcePortionDescription: string, sourceAmount = 1, sourceGramWeight = referenceAmountG * sourceAmount): NutritionPortionConversion {
  return { unit, size, referenceAmountG, sourcePortionId: `FDC portion ${sourcePortionId}`, sourcePortionDescription, sourceAmount, sourceGramWeight };
}

export const FRUIT_FOODS: NutritionCatalogueFood[] = [
  usda({ fdcId: 173944, canonicalName: "Banana, raw", sourceDescription: "Bananas, raw", category: "fruit", preparationState: "raw", aliases: ["banana", "bananas", "raw banana"], nutrients: { energyKcal: 89, proteinG: 1.09, carbohydratesG: 22.84, fatG: 0.33, fibreG: 2.6 }, conversions: [sized("piece", "small", 101, 93514, "1 small banana (6 to 6-7/8 inches)"), sized("piece", "medium", 118, 93515, "1 medium banana (7 to 7-7/8 inches)"), sized("piece", "large", 136, 93516, "1 large banana (8 to 8-7/8 inches)"), ...measure("cup", 150, 93512, "1 cup sliced banana")] }),
  usda({ fdcId: 171688, canonicalName: "Apple, raw, with skin", sourceDescription: "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)", category: "fruit", preparationState: "raw", aliases: ["apple with skin", "raw apple with skin"], nutrients: { energyKcal: 52, proteinG: 0.26, carbohydratesG: 13.81, fatG: 0.17, fibreG: 2.4 }, conversions: [sized("piece", "small", 149, 89194, "1 small apple (2-3/4 inch diameter)"), sized("piece", "medium", 182, 89193, "1 medium apple (3 inch diameter)"), sized("piece", "large", 223, 89192, "1 large apple (3-1/4 inch diameter)"), ...measure("cup", 109, 89191, "1 cup apple slices")] }),
  usda({ fdcId: 169097, canonicalName: "Orange, raw, all commercial varieties", sourceDescription: "Oranges, raw, all commercial varieties", category: "fruit", preparationState: "raw", aliases: ["orange", "raw orange"], nutrients: { energyKcal: 47, proteinG: 0.94, carbohydratesG: 11.75, fatG: 0.12, fibreG: 2.4 }, conversions: [sized("piece", "small", 96, 84229, "1 small orange (2-3/8 inch diameter)"), sized("piece", "medium", 131, 84230, "1 orange (2-5/8 inch diameter)"), sized("piece", "large", 184, 84228, "1 large orange (3-1/16 inch diameter)"), ...measure("cup", 180, 84227, "1 cup orange sections")] }),
  usda({ fdcId: 173044, canonicalName: "Guava, common, raw", sourceDescription: "Guavas, common, raw", category: "fruit", preparationState: "raw", aliases: ["guava", "raw guava"], nutrients: { energyKcal: 68, proteinG: 2.55, carbohydratesG: 14.32, fatG: 0.95, fibreG: 5.4 }, conversions: [...measure("piece", 55, 91859, "1 guava, without refuse"), ...measure("cup", 165, 91858, "1 cup guava")] }),
  usda({ fdcId: 169926, canonicalName: "Papaya, raw", sourceDescription: "Papayas, raw", category: "fruit", preparationState: "raw", aliases: ["papaya", "raw papaya"], nutrients: { energyKcal: 43, proteinG: 0.47, carbohydratesG: 10.82, fatG: 0.26, fibreG: 1.7 }, conversions: [sized("piece", "small", 157, 85694, "1 small papaya"), sized("piece", "large", 781, 85695, "1 large papaya"), ...measure("cup", 145, 85692, "1 cup papaya, 1-inch pieces")] }),
  usda({ fdcId: 169910, canonicalName: "Mango, raw", sourceDescription: "Mangos, raw", category: "fruit", preparationState: "raw", aliases: ["mango", "raw mango fruit"], nutrients: { energyKcal: 60, proteinG: 0.82, carbohydratesG: 14.98, fatG: 0.38, fibreG: 1.6 }, conversions: [...measure("piece", 336, 85652, "1 mango without refuse"), ...measure("cup", 165, 85651, "1 cup mango pieces")] }),
  usda({ fdcId: 167765, canonicalName: "Watermelon, raw", sourceDescription: "Watermelon, raw", category: "fruit", preparationState: "raw", aliases: ["watermelon", "raw watermelon"], nutrients: { energyKcal: 30, proteinG: 0.61, carbohydratesG: 7.55, fatG: 0.15, fibreG: 0.4 }, conversions: [...measure("cup", 152, 81933, "1 cup diced watermelon")] }),
  usda({ fdcId: 169134, canonicalName: "Pomegranate, raw", sourceDescription: "Pomegranates, raw", category: "fruit", preparationState: "raw", aliases: ["pomegranate", "raw pomegranate"], nutrients: { energyKcal: 83, proteinG: 1.67, carbohydratesG: 18.7, fatG: 1.17, fibreG: 4 }, conversions: [...measure("piece", 282, 84310, "1 pomegranate (4-inch diameter)"), ...measure("cup", 174, 84309, "0.5 cup arils weighs 87 g; normalized to 1 cup", 0.5, 87)] }),
  usda({ fdcId: 174683, canonicalName: "Grapes, red or green, raw", sourceDescription: "Grapes, red or green (European type, such as Thompson seedless), raw", category: "fruit", preparationState: "raw", aliases: ["green grapes", "red grapes", "thompson seedless grapes"], nutrients: { energyKcal: 69, proteinG: 0.72, carbohydratesG: 18.1, fatG: 0.16, fibreG: 0.9 }, conversions: [...measure("piece", 4.9, 94749, "10 grapes weigh 49 g; normalized to 1 grape", 10, 49), ...measure("cup", 151, 94748, "1 cup grapes")] }),
];

export const COOKED_GRAIN_FOODS: NutritionCatalogueFood[] = [
  usda({ fdcId: 169704, canonicalName: "Brown rice, long-grain, cooked", sourceDescription: "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)", category: "cooked_grain", preparationState: "cooked", aliases: ["brown rice", "brown rice cooked", "cooked brown rice"], nutrients: { energyKcal: 123, proteinG: 2.74, carbohydratesG: 25.58, fatG: 0.97, fibreG: 1.6 }, conversions: [...measure("cup", 202, 85378, "1 cup cooked brown long-grain rice")] }),
  usda({ fdcId: 168878, canonicalName: "White rice, long-grain, cooked", sourceDescription: "Rice, white, long-grain, regular, enriched, cooked", category: "cooked_grain", preparationState: "cooked", aliases: ["cooked long grain white rice", "cooked white rice", "white rice cooked"], nutrients: { energyKcal: 130, proteinG: 2.69, carbohydratesG: 28.17, fatG: 0.28, fibreG: 0.4 }, conversions: [...measure("cup", 158, 83928, "1 cup cooked white long-grain rice")] }),
  usda({ fdcId: 173905, canonicalName: "Oats, cooked with water, without salt", sourceDescription: "Cereals, oats, regular and quick, unenriched, cooked with water (includes boiling and microwaving), without salt", category: "cooked_grain", preparationState: "cooked", aliases: ["cooked oats", "oatmeal cooked with water", "oats cooked with water"], nutrients: { energyKcal: 71, proteinG: 2.54, carbohydratesG: 12, fatG: 1.52, fibreG: 1.7 }, conversions: [...measure("cup", 234, 93456, "1 cup cooked oats"), ...measure("tablespoon", 14.6, 93457, "1 tablespoon cooked oats")] }),
  usda({ fdcId: 168917, canonicalName: "Quinoa, cooked", sourceDescription: "Quinoa, cooked", category: "cooked_grain", preparationState: "cooked", aliases: ["cooked quinoa"], nutrients: { energyKcal: 120, proteinG: 4.4, carbohydratesG: 21.3, fatG: 1.92, fibreG: 2.8 }, conversions: [...measure("cup", 185, 83990, "1 cup cooked quinoa")] }),
  usda({ fdcId: 170285, canonicalName: "Barley, pearled, cooked", sourceDescription: "Barley, pearled, cooked", category: "cooked_grain", preparationState: "cooked", aliases: ["cooked pearled barley", "pearled barley cooked"], nutrients: { energyKcal: 123, proteinG: 2.26, carbohydratesG: 28.22, fatG: 0.44, fibreG: 3.8 }, conversions: [...measure("cup", 157, 86368, "1 cup cooked pearled barley")] }),
];

export const COOKED_LEGUME_FOODS: NutritionCatalogueFood[] = [
  usda({ fdcId: 172421, canonicalName: "Lentils, cooked, boiled, without salt", sourceDescription: "Lentils, mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["boiled lentils", "cooked lentils", "lentils cooked without salt"], nutrients: { energyKcal: 116, proteinG: 9.02, carbohydratesG: 20.13, fatG: 0.38, fibreG: 7.9 }, conversions: [...measure("cup", 198, 90596, "1 cup cooked lentils"), ...measure("tablespoon", 12.3, 90597, "1 tablespoon cooked lentils")] }),
  usda({ fdcId: 173757, canonicalName: "Chickpeas, cooked, boiled, without salt", sourceDescription: "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["cooked chickpeas", "cooked kabuli chana", "kabuli chana cooked"], nutrients: { energyKcal: 164, proteinG: 8.86, carbohydratesG: 27.42, fatG: 2.59, fibreG: 7.6 }, conversions: [...measure("cup", 164, 93226, "1 cup cooked chickpeas")] }),
  usda({ fdcId: 175194, canonicalName: "Red kidney beans, cooked, boiled, without salt", sourceDescription: "Beans, kidney, red, mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["cooked rajma", "cooked red kidney beans", "rajma cooked"], nutrients: { energyKcal: 127, proteinG: 8.67, carbohydratesG: 22.8, fatG: 0.5, fibreG: 7.4 }, conversions: [...measure("cup", 177, 95822, "1 cup cooked red kidney beans"), ...measure("tablespoon", 11, 95823, "1 tablespoon cooked red kidney beans")] }),
  usda({ fdcId: 173735, canonicalName: "Black beans, cooked, boiled, without salt", sourceDescription: "Beans, black, mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["black beans cooked", "cooked black beans"], nutrients: { energyKcal: 132, proteinG: 8.86, carbohydratesG: 23.71, fatG: 0.54, fibreG: 8.7 }, conversions: [...measure("cup", 172, 93200, "1 cup cooked black beans")] }),
  usda({ fdcId: 174257, canonicalName: "Mung beans, cooked, boiled, without salt", sourceDescription: "Mung beans, mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["cooked green gram", "cooked moong", "cooked mung beans", "green gram cooked", "moong cooked"], nutrients: { energyKcal: 105, proteinG: 7.02, carbohydratesG: 19.15, fatG: 0.38, fibreG: 7.6 }, conversions: [...measure("cup", 202, 94032, "1 cup cooked mung beans")] }),
  usda({ fdcId: 172437, canonicalName: "Pigeon peas, cooked, boiled, without salt", sourceDescription: "Pigeon peas (red gram), mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["arhar cooked", "cooked arhar", "cooked pigeon peas", "cooked toor", "toor cooked"], nutrients: { energyKcal: 121, proteinG: 6.76, carbohydratesG: 23.25, fatG: 0.38, fibreG: 6.7 }, conversions: [...measure("cup", 168, 90621, "1 cup cooked pigeon peas")] }),
  usda({ fdcId: 173759, canonicalName: "Cowpeas, cooked, boiled, without salt", sourceDescription: "Cowpeas, common (blackeyes, crowder, southern), mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["cooked black eyed peas", "cooked cowpeas", "cowpeas cooked"], nutrients: { energyKcal: 116, proteinG: 7.73, carbohydratesG: 20.76, fatG: 0.53, fibreG: 6.5 }, conversions: [...measure("cup", 171, 93229, "1 cup cooked cowpeas")] }),
  usda({ fdcId: 172429, canonicalName: "Split peas, cooked, boiled, without salt", sourceDescription: "Peas, split, mature seeds, cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["cooked split peas", "split peas cooked"], nutrients: { energyKcal: 118, proteinG: 8.34, carbohydratesG: 21.1, fatG: 0.39, fibreG: 8.3 }, conversions: [...measure("cup", 196, 90606, "1 cup cooked split peas"), ...measure("tablespoon", 12.2, 90607, "1 tablespoon cooked split peas")] }),
  usda({ fdcId: 174271, canonicalName: "Soybeans, mature, cooked, boiled, without salt", sourceDescription: "Soybeans, mature cooked, boiled, without salt", category: "cooked_legume", preparationState: "boiled", aliases: ["cooked mature soybeans", "cooked soybeans", "soybeans cooked"], nutrients: { energyKcal: 172, proteinG: 18.21, carbohydratesG: 8.36, fatG: 8.97, fibreG: 6 }, conversions: [...measure("cup", 172, 94059, "1 cup cooked soybeans"), ...measure("tablespoon", 10.7, 94060, "1 tablespoon cooked soybeans")] }),
];

export const SPROUT_FOODS: NutritionCatalogueFood[] = [
  usda({ fdcId: 169957, canonicalName: "Mung bean sprouts, raw", sourceDescription: "Mung beans, mature seeds, sprouted, raw", category: "sprout", preparationState: "sprouted_raw", aliases: ["raw moong sprouts", "raw mung bean sprouts"], nutrients: { energyKcal: 30, proteinG: 3.04, carbohydratesG: 5.94, fatG: 0.18, fibreG: 1.8 }, conversions: [...measure("cup", 104, 85751, "1 cup raw mung bean sprouts")] }),
  usda({ fdcId: 168384, canonicalName: "Alfalfa sprouts, raw", sourceDescription: "Alfalfa seeds, sprouted, raw", category: "sprout", preparationState: "sprouted_raw", aliases: ["raw alfalfa sprouts"], nutrients: { energyKcal: 23, proteinG: 3.99, carbohydratesG: 2.1, fatG: 0.69, fibreG: 1.9 }, conversions: [...measure("cup", 33, 83001, "1 cup raw alfalfa sprouts"), ...measure("tablespoon", 3, 83002, "1 tablespoon raw alfalfa sprouts")] }),
];

export const VEGETABLE_FOODS: NutritionCatalogueFood[] = [
  usda({ fdcId: 170440, canonicalName: "Potato, boiled, without skin or salt", sourceDescription: "Potatoes, boiled, cooked without skin, flesh, without salt", category: "vegetable", preparationState: "boiled", aliases: ["boiled potato without skin", "potato boiled without skin"], nutrients: { energyKcal: 86, proteinG: 1.71, carbohydratesG: 20.01, fatG: 0.1, fibreG: 1.8 }, conversions: [sized("piece", "small", 125, 86654, "1 small boiled potato"), sized("piece", "medium", 167, 86653, "1 medium boiled potato"), sized("piece", "large", 300, 86652, "1 large boiled potato"), ...measure("cup", 156, 86651, "0.5 cup boiled potato weighs 78 g; normalized to 1 cup", 0.5, 78)] }),
  usda({ fdcId: 168484, canonicalName: "Sweet potato, boiled, without skin", sourceDescription: "Sweet potato, cooked, boiled, without skin", category: "vegetable", preparationState: "boiled", aliases: ["boiled sweet potato without skin"], nutrients: { energyKcal: 76, proteinG: 1.37, carbohydratesG: 17.72, fatG: 0.14, fibreG: 2.5 }, conversions: [sized("piece", "medium", 151, 83173, "1 medium boiled sweet potato"), ...measure("cup", 328, 83172, "1 cup mashed boiled sweet potato")] }),
  usda({ fdcId: 170394, canonicalName: "Carrot, cooked, boiled, without salt", sourceDescription: "Carrots, cooked, boiled, drained, without salt", category: "vegetable", preparationState: "boiled", aliases: ["boiled carrot", "cooked carrot boiled"], nutrients: { energyKcal: 35, proteinG: 0.76, carbohydratesG: 8.22, fatG: 0.18, fibreG: 3 }, conversions: [...measure("piece", 46, 86566, "1 cooked carrot"), ...measure("tablespoon", 9.7, 86564, "1 tablespoon cooked carrot"), ...measure("cup", 156, 86565, "0.5 cup cooked carrot slices weighs 78 g; normalized to 1 cup", 0.5, 78)] }),
  usda({ fdcId: 168409, canonicalName: "Cucumber, raw, with peel", sourceDescription: "Cucumber, with peel, raw", category: "vegetable", preparationState: "raw", aliases: ["cucumber with peel", "raw cucumber with peel"], nutrients: { energyKcal: 15, proteinG: 0.65, carbohydratesG: 3.63, fatG: 0.11, fibreG: 0.5 }, conversions: [...measure("piece", 301, 83050, "1 cucumber (8-1/4 inches)"), ...measure("cup", 104, 83049, "0.5 cup cucumber slices weighs 52 g; normalized to 1 cup", 0.5, 52)] }),
  usda({ fdcId: 170457, canonicalName: "Tomato, red, ripe, raw", sourceDescription: "Tomatoes, red, ripe, raw, year round average", category: "vegetable", preparationState: "raw", aliases: ["raw red tomato", "red ripe tomato"], nutrients: { energyKcal: 18, proteinG: 0.88, carbohydratesG: 3.89, fatG: 0.2, fibreG: 1.2 }, conversions: [sized("piece", "small", 91, 86689, "1 small whole tomato"), sized("piece", "medium", 123, 86686, "1 medium whole tomato"), sized("piece", "large", 182, 86685, "1 large whole tomato"), sized("slice", "small", 15, 86692, "1 thin or small tomato slice"), sized("slice", "medium", 20, 86687, "1 medium tomato slice"), sized("slice", "large", 27, 86690, "1 thick or large tomato slice"), ...measure("cup", 180, 86682, "1 cup chopped or sliced tomato")] }),
  usda({ fdcId: 168463, canonicalName: "Spinach, cooked, boiled, without salt", sourceDescription: "Spinach, cooked, boiled, drained, without salt", category: "vegetable", preparationState: "boiled", aliases: ["boiled spinach", "cooked spinach without salt"], nutrients: { energyKcal: 23, proteinG: 2.97, carbohydratesG: 3.75, fatG: 0.26, fibreG: 2.4 }, conversions: [...measure("cup", 180, 83136, "1 cup cooked spinach")] }),
  usda({ fdcId: 170397, canonicalName: "Cauliflower, cooked, boiled, without salt", sourceDescription: "Cauliflower, cooked, boiled, drained, without salt", category: "vegetable", preparationState: "boiled", aliases: ["boiled cauliflower", "cooked cauliflower without salt"], nutrients: { energyKcal: 23, proteinG: 1.84, carbohydratesG: 4.11, fatG: 0.45, fibreG: 2.3 }, conversions: [...measure("cup", 124, 86573, "0.5 cup cooked cauliflower pieces weighs 62 g; normalized to 1 cup", 0.5, 62)] }),
  usda({ fdcId: 169976, canonicalName: "Cabbage, cooked, boiled, without salt", sourceDescription: "Cabbage, cooked, boiled, drained, without salt", category: "vegetable", preparationState: "boiled", aliases: ["boiled cabbage", "cooked cabbage without salt"], nutrients: { energyKcal: 23, proteinG: 1.27, carbohydratesG: 5.51, fatG: 0.06, fibreG: 1.9 }, conversions: [...measure("cup", 150, 85799, "0.5 cup cooked shredded cabbage weighs 75 g; normalized to 1 cup", 0.5, 75)] }),
];

export const NUT_SEED_FOODS: NutritionCatalogueFood[] = [
  usda({ fdcId: 172430, canonicalName: "Peanuts, raw", sourceDescription: "Peanuts, all types, raw", category: "nut_seed", preparationState: "raw", aliases: ["raw groundnut", "raw groundnuts", "raw peanut"], nutrients: { energyKcal: 567, proteinG: 25.8, carbohydratesG: 16.13, fatG: 49.24, fibreG: 8.5 }, conversions: [...measure("cup", 146, 90609, "1 cup raw peanuts")] }),
  usda({ fdcId: 170567, canonicalName: "Almonds, source preparation unspecified", sourceDescription: "Nuts, almonds", category: "nut_seed", preparationState: "source_unspecified", aliases: ["almond", "almonds"], nutrients: { energyKcal: 579, proteinG: 21.15, carbohydratesG: 21.55, fatG: 49.93, fibreG: 12.5 }, conversions: [...measure("piece", 1.2, 86868, "1 almond"), ...measure("cup", 143, 86863, "1 cup whole almonds")] }),
  usda({ fdcId: 170162, canonicalName: "Cashew nuts, raw", sourceDescription: "Nuts, cashew nuts, raw", category: "nut_seed", preparationState: "raw", aliases: ["raw cashew nuts", "raw cashews"], nutrients: { energyKcal: 553, proteinG: 18.22, carbohydratesG: 30.19, fatG: 43.85, fibreG: 3.3 } }),
  usda({ fdcId: 170187, canonicalName: "English walnuts, source preparation unspecified", sourceDescription: "Nuts, walnuts, english", category: "nut_seed", preparationState: "source_unspecified", aliases: ["english walnuts", "walnuts english"], nutrients: { energyKcal: 654, proteinG: 15.23, carbohydratesG: 13.71, fatG: 65.21, fibreG: 6.7 }, conversions: [...measure("cup", 117, 86201, "1 cup chopped English walnuts")] }),
  usda({ fdcId: 170150, canonicalName: "Sesame seeds, whole, dried", sourceDescription: "Seeds, sesame seeds, whole, dried", category: "nut_seed", preparationState: "dried", aliases: ["dried whole sesame seeds"], nutrients: { energyKcal: 573, proteinG: 17.73, carbohydratesG: 23.45, fatG: 49.67, fibreG: 11.8 }, conversions: [...measure("cup", 144, 86135, "1 cup whole dried sesame seeds"), ...measure("tablespoon", 9, 86136, "1 tablespoon whole dried sesame seeds")] }),
  usda({ fdcId: 169414, canonicalName: "Flaxseed, whole, source preparation unspecified", sourceDescription: "Seeds, flaxseed", category: "nut_seed", preparationState: "source_unspecified", aliases: ["flax seeds whole", "whole flaxseed"], nutrients: { energyKcal: 534, proteinG: 18.29, carbohydratesG: 28.88, fatG: 42.16, fibreG: 27.3 }, conversions: [...measure("cup", 168, 84817, "1 cup whole flaxseed"), ...measure("tablespoon", 10.3, 84816, "1 tablespoon whole flaxseed"), ...measure("teaspoon", 3.4, 84819, "1 teaspoon whole flaxseed")] }),
  usda({ fdcId: 170554, canonicalName: "Chia seeds, dried", sourceDescription: "Seeds, chia seeds, dried", category: "nut_seed", preparationState: "dried", aliases: ["dried chia seeds"], nutrients: { energyKcal: 486, proteinG: 16.54, carbohydratesG: 42.12, fatG: 30.74, fibreG: 34.4 } }),
];

export const EXPANDED_NUTRITION_FOODS = [...FRUIT_FOODS, ...COOKED_GRAIN_FOODS, ...COOKED_LEGUME_FOODS, ...SPROUT_FOODS, ...VEGETABLE_FOODS, ...NUT_SEED_FOODS];
