import { notFound } from "next/navigation";
import { requireAccess } from "@/lib/access-control";
import { createClient } from "@/lib/supabase/server";
import { AdminShell } from "../../../components/AdminShell";
import { ClientAdminActions } from "../../../components/ClientAdminActions";

export const dynamic = "force-dynamic";
export default async function ClientDetailPage({ params }: { params: Promise<{ id: string }> }) { await requireAccess(["admin"]); const { id } = await params; const supabase = await createClient(); const [{ data: client }, { data: programmes }, { data: coaches }] = await Promise.all([supabase.from("profiles").select("*").eq("id", id).eq("role", "client").maybeSingle(), supabase.from("programmes").select("*").eq("client_id", id).order("created_at", { ascending: false }).limit(1), supabase.from("profiles").select("id,full_name,email").eq("role", "coach").eq("account_status", "active")]); if (!client) notFound(); const programme = programmes?.[0]; return <AdminShell active="clients"><header className="page-header"><div><p className="section-kicker">Client record</p><h1>{client.full_name ?? "Invited client"}</h1><span>{client.email}</span></div><span className={`large-status status-${client.account_status}`}>{client.account_status}</span></header><div className="client-detail-grid"><section className="content-card client-summary"><h2>Account summary</h2><Summary label="Role" value={client.role} /><Summary label="Last login" value={formatDate(client.last_login_at)} /><Summary label="Onboarding" value={client.onboarding_completed_at ? "Completed" : `Step ${client.onboarding_step}`} /><Summary label="Created" value={formatDate(client.created_at)} /></section><section className="content-card client-access-card"><h2>Programme access</h2><ClientAdminActions clientId={client.id} accountStatus={client.account_status} programmeId={programme?.id} startsAt={programme?.starts_at} expiresAt={programme?.expires_at} programmeStatus={programme?.status} assignedCoachId={programme?.assigned_coach_id ?? undefined} coaches={coaches ?? []} /></section></div></AdminShell>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; } function formatDate(value?: string | null) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "Never"; }
